# File: _config.yml
# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: 
email: 
logo:
description: > # this means to ignore newlines until "nextthing:"
  I like birbs.
footer_text: >
  Fish are friends.
url: # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog/
max_width: 800px
last_updated: # leave blank if you don't want to display last updated
github:
  repository_url:
  user_url:


# Includes
include: ['_pages']

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  micro:
    defaults:
      layout: post
      inline: true
    output: true
    permalink: /micro/:path/
micro_limit: 50


